// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnBgDQxFpF_kRnMWKAMAgkLmJobHANjY8',
    appId: '1:135922194001:android:39bbb2ccca1d3a26d88a70',
    messagingSenderId: '135922194001',
    projectId: 'fir-ea35c',
    databaseURL: 'https://fir-ea35c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-ea35c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJAO1f4UUW2S0j0kh-UnM5H0bXmqAOvkM',
    appId: '1:135922194001:ios:f100ccc713011a3ad88a70',
    messagingSenderId: '135922194001',
    projectId: 'fir-ea35c',
    databaseURL: 'https://fir-ea35c-default-rtdb.firebaseio.com',
    storageBucket: 'fir-ea35c.firebasestorage.app',
    androidClientId: '135922194001-rokqe1nbcukhkami6mumuroce4ctdpnn.apps.googleusercontent.com',
    iosClientId: '135922194001-o7hb2pv77r4s73gkf4vopfa1amo7nm6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyenta',
  );
}
