type Container @table {
  name: String!
  description: String
  colorCode: String
}

type Unit @table {
  content: String!
  createdAt: Timestamp!
  title: String
  updatedAt: Timestamp
  container: Container
}

type Tag @table {
  labelName: String!
  color: String
}

type Source @table {
  urlOrReference: String!
  author: String
  publishDate: Timestamp
  unit: Unit
}

type Relationship @table {
  sourceUnit: Unit!
  targetUnit: Unit!
  relationshipType: String!
  note: String
}

type UnitTag @table {
  unit: Unit!
  tag: Tag!
}